[Refactor] SettingView 리팩토링
DeveloperAcademy-POSTECH/2024-MacC-A14-Namudi-etc pull request #144
Opened 2024-11-15 07:48 UTC by Seo-Jooyoung

## 💡 PR 유형

- [ ] Feature: 기능 추가
- [ ] Hotfix: 작은 버그 수정
- [ ] Bugfix: 큰 버그 수정
- [x] Refactor: 코드 개선
- [ ] Chore: 환경 설정

## ✏️ 변경 사항

- 뷰 컨벤션에 맞춰 코드를 수정했습니다.
- UI 수정사항을 반영했습니다.

## 🚨 관련 이슈

- #140 

## 📝 Pull Request Task ID

Pull Request Task ID: 1208754182009373

## 🧪 테스트

- [x] 목표한 구현 정상 동작 확인

## 🎨 스크린샷

없습니다.

## ✅ 체크리스트

- [x] 코드/커밋이 정해진 컨벤션을 잘 따르고 있나요?
- [x] PR의 Assignees와 Reviewers를 설정했나요?
- [x] 불필요한 코드가 없고, 정상적으로 동작하는지 확인했나요?
- [x] 관련 이슈 번호를 작성했나요?
- [x] Pull Request Task ID를 작성했나요?

## 🔥 추가 설명

2024-11-15 13:39 UTC, namudongs requested changes
불필요한 접근제어자는 저번에 얘기했듯이 없애기로 했습니다~
```swift
struct ContentView: View {
  // 1. 외부 주입이 필요한 프로퍼티
  var title: String // internal(기본값)로 충분
  let content: String // internal(기본값)로 충분
  
  // 2. 내부에서만 사용되는 상태 프로퍼티
  @State private var isLoading = false // private 권장
  
  // 3. 내부 계산 프로퍼티
  private var buttonColor: Color { // private 권장
    isLoading ? .gray : .blue
  }
  
  // 4. 상수값
  private let padding: CGFloat = 16 // private 권장
}
```

이 예시처럼 반영 안된 부분 반영 부탁드려요!
그리고 `FixedExpenseView`에서  "The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions" 이런 타입 추론 오류가 발생할 수 있을 것 같은데, 바디 뷰가 너무 길고 복잡합니다. 

ForEach 내부에 있는 뷰들을 따로 뷰 평션으로 분리하고 sheet 클로저 내부에서 복잡한 계산 로직이 있는 것 같은데 그런 부분도 펑션으로 분리해주세요. 
어려우시면 GPT한테 리팩토링해달라고 해도 잘 해줍니다👍🏻

2024-11-15 13:39 UTC, namudongs commented on Harubee-iOS/Sources/Presentation/Calendar/Components/HelpButton.swift
> +  }
외부에서 값을 받는 경우에는 private으로 만들어서 생성자로 주입받지 않고,
그냥 internal let으로 설정해주세요.

```swift
// MARK: - Help Button
struct HelpButton: View {
  @Binding var infoBubbleVisible: Bool
  let buttonColor: Color
  
  var body: some View {
    Image(systemName: "questionmark.circle")
      .foregroundStyle(buttonColor)
      .tapFeedback {
        infoBubbleVisible.toggle()
      }
  }
}
```

2024-11-15 13:39 UTC, namudongs commented on Harubee-iOS/Sources/Presentation/Common/Components/FloatingTitleTextField.swift
>      self.shouldShowKeyboard = shouldShowKeyboard
이 뷰에서도 값을 모두 외부에서 받으니, 
굳이 private으로 만들어서 생성자를 추가하지 말고 internal로 내부 변수들 설정하고 생성자 없애주세용

2024-11-15 13:39 UTC, namudongs commented on Harubee-iOS/Sources/Presentation/Common/Views/FixedExpenseManageView.swift
>    @State private var isEnabled: Bool = false
이 뷰도 생성자를 없애고, 외부에서 값을 받으면 internal 접근제어자로 설정해주세요.
초기값이 있는 경우엔 선언할 때 지정해주세요.

```swift
struct FixedExpenseManageView: View {
  let mode: Mode
  let action: ((Int, String, String) -> Void)
  
  @Environment(\.dismiss) private var dismiss
  @State private var selectedDay: Int = 1
  @State private var fixedExpenseName: String = ""
  @State private var fixedExpenseAmount: String = ""
  @State private var isEnabled: Bool = false
```

2024-11-16 05:37 UTC, Monfi98 commented
위에 나무디가 요청한것만 고치시면 될것같아용 ㅎ

2024-11-16 05:37 UTC, Monfi98 approved these changes

2024-11-18 13:43 UTC, ljdongz commented on Harubee-iOS/Sources/Presentation/Common/Components/DayPickerView.swift
dayPicker 프로퍼티를 var body: some View 아래로 내려주세요

2024-11-18 13:43 UTC, ljdongz commented on Harubee-iOS/Sources/Presentation/Common/Components/FloatingTitleTextField.swift
>          .padding(.top, 8)
포커싱 여부에 따라 Rectangle의 height을 1 또는 2로 지정해주는데, Rectangle의 높이가 변화하면서 그에따라 FloatingTitleTextField의 전체적인 높이도 1씩 변화하고 있습니다.
따라서, Rectangle에 걸려있는 padding 값 역시 포커싱 여부에 따라 값을 달리 줘야할 필요가 있습니다.
(정확한 위치에 고정시키기 위해)
```suggestion
        .frame(height: !isTextfieldFocused ? 1 : 2)
        .foregroundStyle(
          !isTextfieldFocused
          ? Color.textBrighter
          : Color.main
        )
        .padding(.top, !isTextfieldFocused ? 8 : 7)
```

2024-11-19 04:57 UTC, Seo-Jooyoung commented on Harubee-iOS/Sources/Presentation/Common/Components/DayPickerView.swift
수정했습니당

2024-11-19 05:09 UTC, namudongs approved these changes

2024-11-19 05:24 UTC, merged