[Feature] 알림 기능을 구현하였습니다.
DeveloperAcademy-POSTECH/2024-MacC-A14-Namudi-etc pull request #165
Opened 2024-11-24 08:57 UTC by Monfi98

## 💡 PR 유형

- [x] Feature: 기능 추가
- [ ] Hotfix: 작은 버그 수정
- [ ] Bugfix: 큰 버그 수정
- [ ] Refactor: 코드 개선
- [ ] Chore: 환경 설정

## ✏️ 변경 사항

## 🚨 관련 이슈

- #155 

## 📝 Pull Request Task ID

Pull Request Task ID: 1208783236562095

## 🧪 테스트

- [x] 목표한 구현 정상 동작 확인

## 🎨 스크린샷

|기능|스크린샷|
|:--:|:--:|
|GIF|<img src = "https://github.com/user-attachments/assets/5686f8ae-1a09-4a30-a3b4-483beb135288" width ="250">|

## ✅ 체크리스트

- [x] 코드/커밋이 정해진 컨벤션을 잘 따르고 있나요?
- [x] PR의 Assignees와 Reviewers를 설정했나요?
- [x] 불필요한 코드가 없고, 정상적으로 동작하는지 확인했나요?
- [x] 관련 이슈 번호를 작성했나요?
- [x] Pull Request Task ID를 작성했나요?

## 🔥 추가 설명

### 고민이 되는 부분

SettingView를 보면 위에 `@State` 변수들이 너무 많아져서 이것들을 ViewModel로 빼야할지 말지 고민을 하고 있습니다.
```swift
struct SettingView: View {
  @State var settingViewModel: SettingViewModel
  
  @State private var harubeeSelectedTime: Date
  @State private var expenseSelectedTime: Date
  @State private var harubeeNotificationStatus: Bool
  @State private var expenseNotificationStatus: Bool
  @State private var showHarubeeTimePicker: Bool = false
  @State private var showExpenseTimePicker: Bool = false
  @State private var navigateFixedExpense: Bool = false
  @State private var navigateFixedIncome: Bool = false
  ...
```

만약 ViewModel로 뺀다면,
이번에 새로 만든 TimePickerView도 아래와 같이 picker나 toggle이 모두 Binding으로 되어있기 때문에

```swift
TimePickerView(
        title: "오늘의 하루비 알림",
        isToggleOn: $harubeeNotificationStatus,
        selectedTime: $harubeeSelectedTime,
        showPicker: $showHarubeeTimePicker
      )
```
Binding(get: {}, set: {})을 하나하나 모두 구현해줘야하는 단점이 있습니다.

또한 변경사항은 Alert를 뒤로 가는 시점에서 제어해야 하기 때문에
부득이하게 SettingView에서 기존 Navigation Modifier를 제거 하고 새로 만들었습니다.

하다가 보니 분기 처리가 많아져서 View와 ViewModel의 명확한 분리가 어렵네요..

2024-11-24 10:53 UTC, ljdongz commented on Harubee/Sources/Helper/Extensions/Date+.swift
>  }
Date+에 정의되어있는 formattedDateToString()을 활용해주세여

2024-11-24 10:53 UTC, ljdongz commented on Harubee/Sources/Helper/Manageres/NotificationManager.swift
> +    )
removeDeliveredNotifications()는 알림센터에 있는 알림 목록들을 지워주는 메서드입니다.
현재 deleteNotification에서 작업해야 할 동작은 등록된 알림을 제거하는 것으로 보여지기에
removePendingNotificationRequests()가 적절해 보입니다

2024-11-24 11:56 UTC, Monfi98 commented on Harubee/Sources/Helper/Extensions/Date+.swift
>  }
수정하였습니다.

2024-11-24 12:02 UTC, Monfi98 commented on Harubee/Sources/Helper/Manageres/NotificationManager.swift
> +    )
공식문서를 찾아보니...
> Removes your app’s notifications from Notification Center that match the specified identifiers.
> 지정된 식별자와 일치하는 앱의 알림을 알림 센터에서 제거합니다.
제이드의 말이 맞습니다.
`removePendingNotificationRequests()` 로 바꿨습니다!

2024-11-25 13:56 UTC, ljdongz approved these changes
일단 알림 기능은 잘 동작하고 있어서 일단 릴리즈하고 이후에 코멘트 남긴 부분 리펙토링 부탁드려요~

2024-11-25 13:56 UTC, ljdongz commented on Harubee/Sources/Domain/UseCases/Interfaces/BudgetUseCase.swift
알림 설정 관련한 UseCase는 SettingsUseCase로 분리해보는 것이 어떨까요?

2024-11-25 13:56 UTC, ljdongz commented on Harubee/Sources/Presentation/Common/Components/TimePickerView.swift
> +      }
여기 뷰들도 하위 뷰로 좀 더 나눠주시면 좋을 거 같습니다

2024-11-25 13:59 UTC, seojoozero approved these changes
수고하셨어요 ~.~

2024-11-25 14:20 UTC, Monfi98 commented on Harubee/Sources/Domain/UseCases/Interfaces/BudgetUseCase.swift
넵 좋습니다.

2024-11-25 14:26 UTC, namudongs commented
코드 잘 봤습니다~
아래 내용들에 궁금증이 있습니다!

### action 네이밍 관련

`viewDidLoad`는 UIKit의 뷰 라이프사이클 메소드라 SwiftUI의 `onAppear`에는 맞지 않는 것 같습니다. 
뷰의 `onAppear`에서 어떤 메소드들이 호출되는지 바로 확인할 수 있고 역할과 책임을 분리할 수 있도록 `fetchNotification` 등의 네이밍을 하는게 좋을 것 같아요. 혹은 좀 더 시스템 이벤트에 중심을 둔 네이밍으로 `onAppear`를 사용해도 좋습니다. 이렇게 해도 어떤 메소드들을 호출하는지는 뷰모델에서 확인할 수 있으니까요.

또, 앞전에 세션에선 뷰에서 `onAppear`를 통해 데이터를 가져오는 방식이 좋은 것 같다고 얘기했었습니다. 근데 생각해보니 뷰의 역할은 UI를 렌더링하는 것인데, 뷰에서 `onAppear`로 데이터를 가져오게 되면 데이터 로딩과 같은 역할을 뷰가 떠맡게되는 것 같습니다. 그래서 기존처럼 데이터를 불러오는 로직은 뷰모델에 있는게 더 적절할 것 같습니다.

다만 `fetchNotification`은 `SettingView`에서만 사용되고 같은 뷰모델을 공유하는 고정 지출 뷰, 고정 수입 뷰에서는 사용하지 않는 데이터라 그냥 `onAppear`에 두어도 괜찮을 것 같기는 합니다. 이 부분은 몽피가 생각해보고 원하는 방향대로 구현해주시면 따라가겠습니다!

### 바인딩 메소드와 `onChange` 관련

현재 `onChange`를 사용해 `state`의 변화를 감지하고 `send`로 액션을 트리거하고 있는데, 바인딩은 기본적으로 양방향 흐름을 제공합니다. 따라서 바인딩에서 `set` 메소드가 호출될 때 액션을 트리거하면 `onChange`를 제거할 수 있어 코드가 간결해지고 중복이 방지됩니다.

변경 후, `onChangeNotificationTime`과 `onChangeNotificationStatus`를 `private` 메소드로 제한하고 `binding`을 통해 액션을 트리거하도록 구현하면 유지보수성이 향상될 것 같은데 어떻게 생각하시나요?

```swift
// 기존
.onChange(
      of: settingViewModel.state.harubeeNotificationTime
    ) { _, newValue in
      settingViewModel.send(
        .onChangeNotificationTime(notificationType: .harubee, newValue)
      )
    }
    .onChange(
      of: settingViewModel.state.expenseNotificationTime
    ) { _, newValue in
      settingViewModel.send(
        .onChangeNotificationTime(notificationType: .expense, newValue)
      )
    }
    .onChange(
      of: settingViewModel.state.harubeeNotificationStatus
    ) { _, newValue in
      settingViewModel.send(
        .onChangeNotificationStatus(notificationType: .harubee, newValue)
      )
    }
    .onChange(
      of: settingViewModel.state.expenseNotificationStatus
    ) { _, newValue in
      settingViewModel.send(
        .onChangeNotificationStatus(notificationType: .expense, newValue)
      )
    }

// 변경 제안
func binding<T>(_ key: BindingKey) -> SwiftUI.Binding<T> {
    switch key {
    case .harubeeNotificationTime:
      return Binding(
        get: { self.state.harubeeNotificationTime as! T },
        set: {
          self.state.harubeeNotificationTime = $0 as! Date
          self.send(.onChangeNotificationTime(notificationType: .harubee, $0 as! Date))
        }
      )
    case .expenseNotificationTime:
      return Binding(
        get: { self.state.expenseNotificationTime as! T },
        set: {
          self.state.expenseNotificationTime = $0 as! Date
          self.send(.onChangeNotificationTime(notificationType: .expense, $0 as! Date))
        }
      )
    case .harubeeNotificationStatus:
      return Binding(
        get: { self.state.harubeeNotificationStatus as! T },
        set: {
          self.state.harubeeNotificationStatus = $0 as! Bool
          self.send(.onChangeNotificationStatus(notificationType: .harubee, $0 as! Bool))
        }
      )
    case .expenseNotificationStatus:
      return Binding(
        get: { self.state.expenseNotificationStatus as! T },
        set: {
          self.state.expenseNotificationStatus = $0 as! Bool
          self.send(.onChangeNotificationStatus(notificationType: .expense, $0 as! Bool))
        }
      )
    }
  }
```
이렇게 하면 `onChangeNotificationTime`과 `onChangeNotificationStatus`는 뷰모델 내부에서만 사용하고, `binding`의 `set` 액션을 통해서만 호출되니 `액션(send)`이 아닌 `private` 메소드로 선언할 수 있을 것 같습니다.
```swift
var harubeeNotificationTime: Date = Date()
var expenseNotificationTime: Date = Date()
var harubeeNotificationStatus: Bool = false
var expenseNotificationStatus: Bool = false
```
따라서 이 상태들도 외부에서 접근할 필요가 없어져, `private`으로 캡슐화할 수 있을 것 같은데 어떻게 생각하시는지?

### 뷰모델 메소드 가독성 관련
`onChangeNotificationTime`과 `onChangeNotificationStatus` 메소드에 중복되는 로직이 많습니다. 이를 하나의 유틸리티 메소드로 추출하면 가독성이 좋아지고, 유지보수 시 중복 코드를 수정해야 하는 부담이 줄어들 것 같은데 어떻게 생각하시나요?

### 유즈케이스와 레포지토리 관련
`fetchNotificationData` 메소드에서 유즈케이스의 `get` 메소드를 호출하고 있는데, 유즈케이스의 알림 관련 메소드들이 에러를 던질 이유가 없는 것 같습니다. 

현재는 옵셔널로 값을 반환하고 있습니다. 그런데 `get` 메소드의 내부 로직이 "**알림 시간을 가져오다가 값이 없으면 기본 시간으로 설정하기**"로 되어있어서 옵셔널로 반환할 필요도, `throws`로 작성될 필요도 없을 것 같습니다.

마찬가지로 `UserDefaultsRepository` 에서도 값을 옵셔널로 반환한다면 `throws`로 작성될 필요가 없을 것 같습니다. 유즈케이스에서 옵셔널인 경우 기본값을 설정하면 될 것 같습니다.

```swift
// 유즈케이스 예시
func getTodayHarubeeNotificationTime() -> Date {
    return userDefaultsRepository.readTodayHarubeeNotificationTime() ?? createDefaultTime(hour: 9)
}
```

2024-11-25 14:26 UTC, namudongs requested changes
수정 후 멘션 부탁드립니다~!

2024-11-28 13:25 UTC, Monfi98 commented
> 수정 후 멘션 부탁드립니다~!
onChange에 좌르륵 쓰는 부분이 안그래도 마음에 걸렸었는데 좋은 제안입니당 ㅎㅎ
일단 Binding 부분은 아래와 같이 수정했습니다
```swift
extension SettingViewModel {
  
  // MARK: - Binding
  enum BindingKey {
    case harubeeNotificationTime
    case expenseNotificationTime
    case harubeeNotificationStatus
    case expenseNotificationStatus
  }
  
  func binding<T>(_ key: BindingKey) -> SwiftUI.Binding<T> {
    switch key {
    case .harubeeNotificationTime:
      return Binding(
        get: { self.state.harubeeNotificationTime as! T },
        set: {
          self.state.harubeeNotificationTime = $0 as! Date
          self.onChangeNotificationTime(
            notificationType: .harubee,
            time: $0 as! Date
          )
        }
      )
    case .expenseNotificationTime:
      return Binding(
        get: { self.state.expenseNotificationTime as! T },
        set: {
          self.state.expenseNotificationTime = $0 as! Date
          self.onChangeNotificationTime(
            notificationType: .expense,
            time: $0 as! Date
          )
        }
      )
    case .harubeeNotificationStatus:
      return Binding(
        get: { self.state.harubeeNotificationStatus as! T },
        set: {
          self.state.harubeeNotificationStatus = $0 as! Bool
          self.onChangeNotificationStatus(
            notificationType: .harubee,
            status: $0 as! Bool
          )
        }
      )
    case .expenseNotificationStatus:
      return Binding(
        get: { self.state.expenseNotificationStatus as! T },
        set: {
          self.state.expenseNotificationStatus = $0 as! Bool
          self.onChangeNotificationStatus(
            notificationType: .expense,
            status: $0 as! Bool
          )
        }
      )
    }
  }
}
```

따라서, View의 onChange에서 send하지 않아도 내부에서 작동하도록 변경하였습니다.
추가로 fetch하는 부분도 ViewModel에서 하도록 변경하였습니다.
나머지는 리팩토링때 한번더 생각해보고 반영하도록 하겠습니다.
@namudongs

2024-11-28 13:57 UTC, merged